push

diff --git a/Jenkinsfile-clean b/Jenkinsfile-clean
--- a/Jenkinsfile-clean
+++ b/Jenkinsfile-clean
@@ -18,11 +18,12 @@ pipeline {
                         .find { it._class.contains('UserIdCause') }?.userId ?: 'anonymous'
                         env.NAMESPACE = "${userId}-${NAMESPACE}"
                         sh '''
-                        echo "Setting up kubeconfig..."
-                        export KUBECONFIG=$KUBECONFIG_FILE
-                        kubectl config get-contexts
-                      '''
+                            echo "Setting up kubeconfig..."
+                            export KUBECONFIG=$KUBECONFIG_FILE
+                            kubectl config get-contexts
+                        '''
                     }
+                    
                 }
             }
         }
@@ -34,7 +35,7 @@ pipeline {
                         export KUBECONFIG=$KUBECONFIG_FILE
                         echo "Verifying access to Kubernetes cluster..."
                         kubectl cluster-info
-                        kubectl get ns $env.NAMESPACE
+                        kubectl get ns $NAMESPACE
                     '''
                 }
             }
@@ -45,8 +46,8 @@ pipeline {
                 withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG_FILE')]) {
                     sh '''
                         export KUBECONFIG=$KUBECONFIG_FILE
-                        echo "Deleting all in namespace $env.NAMESPACE..."
-                        kubectl delete all --all -n $env.NAMESPACE || echo "No thing found."
+                        echo "Deleting all in namespace $NAMESPACE..."
+                        kubectl delete all --all -n $NAMESPACE || echo "No thing found."
                     '''
                 }
             }
@@ -54,14 +55,14 @@ pipeline {
 
         stage('Cleanup Complete') {
             steps {
-                echo "Cleanup completed in namespace: ${env.NAMESPACE}"
+                echo "Cleanup completed in namespace: ${NAMESPACE}"
             }
         }
     }
 
     post {
         failure {
-            echo "An error occurred during cleanup in namespace: ${env.NAMESPACE}"
+            echo "An error occurred during cleanup in namespace: ${NAMESPACE}"
         }
     }
 }
